# Unique name for this worklow
name: 'Validate PR open to QA'

# Definition when the workflow should run
on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches:
    - 'release-branch*'
    paths:
      - force-app/**

jobs:
  validate-pr-on-qa-org:
    runs-on: ubuntu-latest
    steps:
      - name: 'Read PR Body'
        env:
        # The pull request body is available through the github context object
        # we put the body of the pull request in an env variable (only available to this step)
        PR_BODY: ${{github.event.pull_request.body}}
        run: |
          echo $PR_BODY > ./pr_body.txt
          node ./parsePR.js              
          TESTS=$(cat testsToRun.txt)
          echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV

      # Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version

      # Install SFDX-Git-Delta plugin
      - name: 'Installing SFDX GIT DELTA PLUGIN'
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          sfdx plugins

      # Installing java
      - name: 'Installing JAVA'
        run: |
          sudo apt-get update
          sudo apt install default-jdk

      # Store secret of the org
      - name: 'Populate auth file'
        shell: bash
        run: |
          echo ${{ secrets.ORG_QA_URL}} > ./ORG_QA_URL.txt

      # Authenticate to ORG
      - name: 'Authenticate to QA org'
        run: sfdx auth:sfdxurl:store -f ./ORG_QA_URL.txt -s -a integration

      # Generate delta package
      - name: 'Create Delta package'
        run: |
          sfdx sgd:source:delta --to "HEAD" --from "HEAD~7" --output "." --source force-app/
          echo "-- package.xml generate by plugin --"
          cat package/package.xml

      # Run validation command based on package.xml
      - name: 'Validate Delta changes'
        if: ${{ env.APEX_TESTS != 'all' }}
        run: |
          echo ${{env.APEX_TESTS}}
          sfdx force:source:deploy --checkonly -x package/package.xml --testlevel RunSpecifiedTests --runtests ${{env.APEX_TESTS}} --verbose --json

      # If the env variable equals all, we run all tests
      - name: 'Check-only deploy delta changes - run all tests'
        if: ${{ env.APEX_TESTS == 'all' }}
        run: |
          echo ${{env.APEX_TESTS}}
          sfdx force:source:deploy --checkonly -x package/package.xml --testlevel RunLocalTests --json